### ISSUE TITLE
would u release demo.py to test one img or video?

### ISSUE THREAD

**Issue by codylcs** [HRNet/Lite-HRNet#5]
it is amazing lightweight work, would u consider add a script to test a img with model?
as demo.py like [https://github.com/HRNet/HigherHRNet-Human-Pose-Estimation/pull/28/commits/57c1f30a5d5e3d789dc220971cef6e1d451fe77e](https://github.com/HRNet/HigherHRNet-Human-Pose-Estimation/pull/28/commits/57c1f30a5d5e3d789dc220971cef6e1d451fe77e)

**Comment by hejing-maker** [comment]
地址有问题啊

**Comment by codylcs** [comment]
> 地址有问题啊

has been update

**Comment by hejing-maker** [comment]
问个问题，能否提供转ONNX的实例代码呢

**Comment by codylcs** [comment]
use[cfg](https://github.com/HRNet/Lite-HRNet/blob/hrnet/configs/top_down/lite_hrnet/coco/litehrnet_30_coco_384x288.py) to test with rtx titan ,fps is about 9.6;
result as flow
![image](https://user-images.githubusercontent.com/48380363/114865280-98881b00-9e24-11eb-91ce-7aaec79fc27a.png)
![image](https://user-images.githubusercontent.com/48380363/114865477-dc7b2000-9e24-11eb-82ac-d8bd0e818652.png)
it is good,but not so good,how to improve ap and recall? any advices?

**Comment by codylcs** [comment]
after trained my dataset, it seems ok although results are not so good as HRNETw32,but speed is more faster than  HRNETw32 which can reach to 17fps on titan rtx GPU

**Comment by codylcs** [comment]
> 问个问题，能否提供转ONNX的实例代码呢

use mmpose pytorch2onnx.py,error happens

Use load_from_local loader
/home/cody/anaconda3/envs/LiteHRNET/lib/python3.7/site-packages/mmpose/models/backbones/utils/channel_shuffle.py:20: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert (num_channels % groups == 0), ('num_channels should be '
Traceback (most recent call last):
  File "/home/cody/PycharmProjects/Lite-HRNet/tools/pytorch2onnx.py", line 156, in <module>
    verify=args.verify)
  File "/home/cody/PycharmProjects/Lite-HRNet/tools/pytorch2onnx.py", line 73, in pytorch2onnx
    opset_version=opset_version)
  File "/home/cody/anaconda3/envs/LiteHRNET/lib/python3.7/site-packages/torch/onnx/__init__.py", line 230, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/cody/anaconda3/envs/LiteHRNET/lib/python3.7/site-packages/torch/onnx/utils.py", line 91, in export
    use_external_data_format=use_external_data_format)
  File "/home/cody/anaconda3/envs/LiteHRNET/lib/python3.7/site-packages/torch/onnx/utils.py", line 639, in _export
    dynamic_axes=dynamic_axes)
  File "/home/cody/anaconda3/envs/LiteHRNET/lib/python3.7/site-packages/torch/onnx/utils.py", line 421, in _model_to_graph
    dynamic_axes=dynamic_axes, input_names=input_names)
  File "/home/cody/anaconda3/envs/LiteHRNET/lib/python3.7/site-packages/torch/onnx/utils.py", line 203, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/cody/anaconda3/envs/LiteHRNET/lib/python3.7/site-packages/torch/onnx/__init__.py", line 263, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/cody/anaconda3/envs/LiteHRNET/lib/python3.7/site-packages/torch/onnx/utils.py", line 934, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "/home/cody/anaconda3/envs/LiteHRNET/lib/python3.7/site-packages/torch/onnx/symbolic_helper.py", line 128, in wrapper
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "/home/cody/anaconda3/envs/LiteHRNET/lib/python3.7/site-packages/torch/onnx/symbolic_helper.py", line 128, in <listcomp>
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "/home/cody/anaconda3/envs/LiteHRNET/lib/python3.7/site-packages/torch/onnx/symbolic_helper.py", line 81, in _parse_arg
    "', since it's not constant, please try to make "
RuntimeError: Failed to export an ONNX attribute 'onnx::Gather', since it's not constant, please try to make things (e.g., kernel size) static if possible

Process finished with exit code 1

**Comment by FanHuang1008** [comment]
https://github.com/FanHuang1008/Demo-Function-for-Lite-HRNet/
