### ISSUE TITLE
FileNotFoundError: TopDownMpiiDataset: file "/Lite-HRNet/configs/_base_/datasets/mpii.py" does not exist

### ISSUE THREAD

**Issue by ZardZen** [HRNet/Lite-HRNet#63]

**Comment by GoogQing** [comment]
Have you fixed it? Suffer the same problem

**Comment by ZekunZh** [comment]
Same problem, any idea how to fix it ? 🙏

**Comment by l1teng** [comment]
Same problem, any solutions?

**Comment by l1teng** [comment]
I tried the COCO dataset for testing, met the similar issue.

The standard output as the following,

```
Traceback (most recent call last):
  File "test.py", line 141, in <module>
    main()
  File "test.py", line 96, in main
    dataset = build_dataset(cfg.data.test, dict(test_mode=True))
  File "/opt/conda/envs/hrnet/lib/python3.7/site-packages/mmpose/datasets/builder.py", line 44, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/opt/conda/envs/hrnet/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
FileNotFoundError: TopDownCocoDataset: file "/root/stu/tengli/Lite-HRNet/configs/_base_/datasets/coco.py" does not exist
```

Is there anyone meet this and solved can help? Thanks...

**Comment by l1teng** [comment]
Hi, all. A good news here.

I tried Lite-HRNet model testing with code in this [repo](https://github.com/open-mmlab/mmpose) and it worked.

Hope can help you.

**Comment by zwd1993** [comment]
从 mmpose config 下复制个__base__粘贴到缺失的位置即可  解决了FileNotFoundError: file "/mnt/d/workplace/Lite-HRNet/configs/_base_/datasets/coco.py" does not exist 该问题

**Comment by zwd1993** [comment]
https://github.com/open-mmlab/mmpose/tree/master/configs/_base_/

**Comment by ZekunZh** [comment]
@zwd1993 Many thanks !
