### ISSUE TITLE
cannot import name 'Config' from 'mmcv'

### ISSUE THREAD

**Issue by Ergou-Liu** [HRNet/Lite-HRNet#82]

**Comment by Ergou-Liu** [comment]
Lite-HRNet$ python ./tools/train.py 
Traceback (most recent call last):
  File "./tools/train.py", line 9, in <module>
    from mmcv import Config, DictAction
ImportError: cannot import name 'Config' from 'mmcv' (/home/name/anaconda3/envs/lite-hrnet/lib/python3.8/site-packages/mmcv/__init__.py)

**Comment by haowei2020** [comment]
> Lite-HRNet$ python ./tools/train.py Traceback (most recent call last): File "./tools/train.py", line 9, in from mmcv import Config, DictAction ImportError: cannot import name 'Config' from 'mmcv' (/home/name/anaconda3/envs/lite-hrnet/lib/python3.8/site-packages/mmcv/**init**.py)
貌似新的mmcv没有Config这个类的定义，挪到了mmengin，你可以装个低版本的mmcv，比如1.6的

**Comment by haowei2020** [comment]
> Lite-HRNet$ python ./tools/train.py Traceback (most recent call last): File "./tools/train.py", line 9, in from mmcv import Config, DictAction ImportError: cannot import name 'Config' from 'mmcv' (/home/name/anaconda3/envs/lite-hrnet/lib/python3.8/site-packages/mmcv/**init**.py)

貌似新的mmcv没有Config这个类的定义，挪到了mmengin，你可以装个低版本的mmcv，比如1.6的

**Comment by TonyZ-sz** [comment]
1.6 的没有 mmcv.transforms 这个吖。你们用的哪个 mmcv 呢
